[package]
name = "reifydb-sub-workerpool"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-type = { workspace = true }

[dev-dependencies]
