[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"
features = ["include-python-workspace"]

[project]
version = "0.0.1"
name = "reifydb-py"
requires-python = ">=3.10"
description = "Data. Backend. Done"
classifiers = ["Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
