[package]
name = "reifydb-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-type = { workspace = true}
chrono = { workspace = true}
crossbeam-channel = { workspace = true }
crossbeam-skiplist = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
uuid = { workspace = true}


