# ReifyDB Workspace Dependencies
# Generated dependency trees for all crates in the workspace
# Usage: make -f mk/dependencies.mk deps

.PHONY: deps
deps:
	@echo "=========================================="
	@echo "ReifyDB Workspace Dependency Analysis"
	@echo "=========================================="
	@echo ""
	@echo "Generated on: $$(date)"
	@echo ""
	@echo "## FOUNDATION CRATES"
	@echo ""
	@echo "### reifydb-type (Base types)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-type 2>/dev/null || echo "Error: Could not analyze reifydb-type"
	@echo ""
	@echo "### reifydb-hash (Hashing utilities)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-hash 2>/dev/null || echo "Error: Could not analyze reifydb-hash"
	@echo ""
	@echo "### reifydb-auth (Authentication)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-auth 2>/dev/null || echo "Error: Could not analyze reifydb-auth"
	@echo ""
	@echo "## CORE INFRASTRUCTURE"
	@echo ""
	@echo "### reifydb-core (Core functionality)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-core 2>/dev/null || echo "Error: Could not analyze reifydb-core"
	@echo ""
	@echo "### reifydb-testing (Testing utilities)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-testing 2>/dev/null || echo "Error: Could not analyze reifydb-testing"
	@echo ""
	@echo "## STORAGE LAYER"
	@echo ""
	@echo "### reifydb-storage (Storage engine)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-storage 2>/dev/null || echo "Error: Could not analyze reifydb-storage"
	@echo ""
	@echo "### reifydb-transaction (Transaction management)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-transaction 2>/dev/null || echo "Error: Could not analyze reifydb-transaction"
	@echo ""
	@echo "## ENGINE & QUERY"
	@echo ""
	@echo "### reifydb-catalog (Catalog management)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-catalog 2>/dev/null || echo "Error: Could not analyze reifydb-catalog"
	@echo ""
	@echo "### reifydb-rql (Query language)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-rql 2>/dev/null || echo "Error: Could not analyze reifydb-rql"
	@echo ""
	@echo "### reifydb-engine (Query engine)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-engine 2>/dev/null || echo "Error: Could not analyze reifydb-engine"
	@echo ""
	@echo "## SUBSYSTEMS"
	@echo ""
	@echo "### reifydb-cdc (Change Data Capture)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-cdc 2>/dev/null || echo "Error: Could not analyze reifydb-cdc"
	@echo ""
	@echo "### reifydb-sub-logging (Logging subsystem)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-sub-logging 2>/dev/null || echo "Error: Could not analyze reifydb-sub-logging"
	@echo ""
	@echo "### reifydb-sub-workerpool (Worker pool)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-sub-workerpool 2>/dev/null || echo "Error: Could not analyze reifydb-sub-workerpool"
	@echo ""
	@echo "### reifydb-sub-flow (Flow subsystem)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-sub-flow 2>/dev/null || echo "Error: Could not analyze reifydb-sub-flow"
	@echo ""
	@echo "### reifydb-sub-server (Server subsystem)"
	@echo "----------------------------------------"
	@cargo tree -p reifydb-sub-server 2>/dev/null || echo "Error: Could not analyze reifydb-sub-server"
	@echo ""
	@echo "=========================================="
	@echo "## DEPENDENCY SUMMARY STATISTICS"
	@echo "=========================================="
	@echo ""
	@echo "| Crate | Direct Deps | Total Transitive |"
	@echo "|-------|-------------|------------------|"
	@echo "| reifydb-type | $$(cargo tree -p reifydb-type --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-type 2>/dev/null | grep -v '^reifydb-type' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-core | $$(cargo tree -p reifydb-core --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-core 2>/dev/null | grep -v '^reifydb-core' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-hash | $$(cargo tree -p reifydb-hash --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-hash 2>/dev/null | grep -v '^reifydb-hash' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-auth | $$(cargo tree -p reifydb-auth --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-auth 2>/dev/null | grep -v '^reifydb-auth' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-testing | $$(cargo tree -p reifydb-testing --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-testing 2>/dev/null | grep -v '^reifydb-testing' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-storage | $$(cargo tree -p reifydb-storage --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-storage 2>/dev/null | grep -v '^reifydb-storage' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-transaction | $$(cargo tree -p reifydb-transaction --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-transaction 2>/dev/null | grep -v '^reifydb-transaction' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-catalog | $$(cargo tree -p reifydb-catalog --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-catalog 2>/dev/null | grep -v '^reifydb-catalog' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-rql | $$(cargo tree -p reifydb-rql --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-rql 2>/dev/null | grep -v '^reifydb-rql' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-engine | $$(cargo tree -p reifydb-engine --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-engine 2>/dev/null | grep -v '^reifydb-engine' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-cdc | $$(cargo tree -p reifydb-cdc --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-cdc 2>/dev/null | grep -v '^reifydb-cdc' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-sub-logging | $$(cargo tree -p reifydb-sub-logging --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-sub-logging 2>/dev/null | grep -v '^reifydb-sub-logging' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-sub-workerpool | $$(cargo tree -p reifydb-sub-workerpool --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-sub-workerpool 2>/dev/null | grep -v '^reifydb-sub-workerpool' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-sub-flow | $$(cargo tree -p reifydb-sub-flow --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-sub-flow 2>/dev/null | grep -v '^reifydb-sub-flow' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo "| reifydb-sub-server | $$(cargo tree -p reifydb-sub-server --depth 1 2>/dev/null | grep -E '^[├└]' | grep -v '\[dev-dependencies\]' | wc -l) | $$(cargo tree -p reifydb-sub-server 2>/dev/null | grep -v '^reifydb-sub-server' | sed 's/[│├└ ─]*//g' | cut -d' ' -f1 | grep -v '^\[' | grep -v '^$$' | sort | uniq | wc -l) |"
	@echo ""
	@echo "=========================================="
	@echo "End of Dependency Analysis"
	@echo "=========================================="