[package]
name = "reifydb_storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb_core = { workspace = true }
heed = { workspace = true }

rusqlite = { version = "0.36.0", features = ["bundled"] }
r2d2 = {version = "0.8.10"}
r2d2_sqlite = {version = "0.29.0"}

crossbeam-channel = { workspace = true }
crossbeam-skiplist = { workspace = true }
regex = { workspace = true }
[dev-dependencies]
reifydb_testing = { workspace = true }
test_each_file = { workspace = true }
