[package]
name = "storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base = { workspace = true }

regex = {workspace = true}
serde = { workspace = true }

[dev-dependencies]
testing = { workspace = true }
test_each_file = { workspace = true }
