[package]
name = "reifydb-system"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-network = { workspace = true, optional = true }

# async runtime for network adapters and context management
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }


[features]
default = []
server = ["dep:reifydb-network", "reifydb-network/server"]
grpc = ["reifydb-network/grpc"]
websocket = ["reifydb-network/websocket"]

[[example]]
name = "basic_system"
path = "examples/basic_system.rs"

