[package]
name = "reifydb-system"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }

# std library and utility dependencies
uuid = { workspace = true }

[dev-dependencies]
reifydb-storage = { workspace = true }
reifydb-transaction = { workspace = true }

[[example]]
name = "basic_system"
path = "examples/basic_system.rs"

