[package]
name = "reifydb-auth"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-type = { workspace = true }

[dev-dependencies]