// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 ReifyDB

pub mod blob;
pub mod clock;
pub mod date;
pub mod datetime;
pub mod duration;
pub mod flow;
pub mod identity;
pub mod is;
pub mod json;
pub mod math;
pub mod meta;
pub mod rql;
pub mod series;
pub mod text;
pub mod time;
pub mod uuid;

use std::sync::Arc;

use crate::{
	function::uuid::{v4::UuidV4, v7::UuidV7},
	routine::registry::RoutinesConfigurator,
};

pub fn default_native_functions(builder: RoutinesConfigurator) -> RoutinesConfigurator {
	builder.register_builtin_function(Arc::new(math::sum::Sum::new()))
		.register_builtin_function(Arc::new(math::avg::Avg::new()))
		.register_builtin_function(Arc::new(math::count::Count::new()))
		.register_builtin_function(Arc::new(math::min::Min::new()))
		.register_builtin_function(Arc::new(math::max::Max::new()))
		.register_builtin_function(Arc::new(math::abs::Abs::new()))
		.register_builtin_function(Arc::new(flow::to_json::FlowNodeToJson::new()))
		.register_builtin_function(Arc::new(clock::now::Now::new()))
		.register_builtin_function(Arc::new(blob::b58::BlobB58::new()))
		.register_builtin_function(Arc::new(blob::b64::BlobB64::new()))
		.register_builtin_function(Arc::new(blob::b64url::BlobB64url::new()))
		.register_builtin_function(Arc::new(blob::hex::BlobHex::new()))
		.register_builtin_function(Arc::new(blob::utf8::BlobUtf8::new()))
		.register_builtin_function(Arc::new(math::acos::Acos::new()))
		.register_builtin_function(Arc::new(math::asin::Asin::new()))
		.register_builtin_function(Arc::new(math::atan::Atan::new()))
		.register_builtin_function(Arc::new(math::atan2::Atan2::new()))
		.register_builtin_function(Arc::new(math::ceil::Ceil::new()))
		.register_builtin_function(Arc::new(math::clamp::Clamp::new()))
		.register_builtin_function(Arc::new(math::cos::Cos::new()))
		.register_builtin_function(Arc::new(math::euler::Euler::new()))
		.register_builtin_function(Arc::new(math::exp::Exp::new()))
		.register_builtin_function(Arc::new(math::floor::Floor::new()))
		.register_builtin_function(Arc::new(math::gcd::Gcd::new()))
		.register_builtin_function(Arc::new(math::lcm::Lcm::new()))
		.register_builtin_function(Arc::new(math::log::Log::new()))
		.register_builtin_function(Arc::new(math::log10::Log10::new()))
		.register_builtin_function(Arc::new(math::log2::Log2::new()))
		.register_builtin_function(Arc::new(math::modulo::Modulo::new()))
		.register_builtin_function(Arc::new(math::pi::Pi::new()))
		.register_builtin_function(Arc::new(math::power::Power::new()))
		.register_builtin_function(Arc::new(math::round::Round::new()))
		.register_builtin_function(Arc::new(math::sign::Sign::new()))
		.register_builtin_function(Arc::new(math::sin::Sin::new()))
		.register_builtin_function(Arc::new(math::sqrt::Sqrt::new()))
		.register_builtin_function(Arc::new(math::tan::Tan::new()))
		.register_builtin_function(Arc::new(math::truncate::Truncate::new()))
		.register_builtin_function(Arc::new(date::year::DateYear::new()))
		.register_builtin_function(Arc::new(date::month::DateMonth::new()))
		.register_builtin_function(Arc::new(date::day::DateDay::new()))
		.register_builtin_function(Arc::new(date::day_of_year::DateDayOfYear::new()))
		.register_builtin_function(Arc::new(date::day_of_week::DateDayOfWeek::new()))
		.register_builtin_function(Arc::new(date::quarter::DateQuarter::new()))
		.register_builtin_function(Arc::new(date::week::DateWeek::new()))
		.register_builtin_function(Arc::new(date::is_leap_year::DateIsLeapYear::new()))
		.register_builtin_function(Arc::new(date::days_in_month::DateDaysInMonth::new()))
		.register_builtin_function(Arc::new(date::end_of_month::DateEndOfMonth::new()))
		.register_builtin_function(Arc::new(date::start_of_month::DateStartOfMonth::new()))
		.register_builtin_function(Arc::new(date::start_of_year::DateStartOfYear::new()))
		.register_builtin_function(Arc::new(date::new::DateNew::new()))
		.register_builtin_function(Arc::new(date::now::DateNow::new()))
		.register_builtin_function(Arc::new(date::add::DateAdd::new()))
		.register_builtin_function(Arc::new(date::subtract::DateSubtract::new()))
		.register_builtin_function(Arc::new(date::diff::DateDiff::new()))
		.register_builtin_function(Arc::new(date::trunc::DateTrunc::new()))
		.register_builtin_function(Arc::new(date::age::DateAge::new()))
		.register_builtin_function(Arc::new(date::format::DateFormat::new()))
		.register_builtin_function(Arc::new(time::hour::TimeHour::new()))
		.register_builtin_function(Arc::new(time::minute::TimeMinute::new()))
		.register_builtin_function(Arc::new(time::second::TimeSecond::new()))
		.register_builtin_function(Arc::new(time::nanosecond::TimeNanosecond::new()))
		.register_builtin_function(Arc::new(time::new::TimeNew::new()))
		.register_builtin_function(Arc::new(time::now::TimeNow::new()))
		.register_builtin_function(Arc::new(time::add::TimeAdd::new()))
		.register_builtin_function(Arc::new(time::subtract::TimeSubtract::new()))
		.register_builtin_function(Arc::new(time::diff::TimeDiff::new()))
		.register_builtin_function(Arc::new(time::trunc::TimeTrunc::new()))
		.register_builtin_function(Arc::new(time::age::TimeAge::new()))
		.register_builtin_function(Arc::new(time::format::TimeFormat::new()))
		.register_builtin_function(Arc::new(datetime::year::DateTimeYear::new()))
		.register_builtin_function(Arc::new(datetime::month::DateTimeMonth::new()))
		.register_builtin_function(Arc::new(datetime::day::DateTimeDay::new()))
		.register_builtin_function(Arc::new(datetime::hour::DateTimeHour::new()))
		.register_builtin_function(Arc::new(datetime::minute::DateTimeMinute::new()))
		.register_builtin_function(Arc::new(datetime::second::DateTimeSecond::new()))
		.register_builtin_function(Arc::new(datetime::nanosecond::DateTimeNanosecond::new()))
		.register_builtin_function(Arc::new(datetime::day_of_year::DateTimeDayOfYear::new()))
		.register_builtin_function(Arc::new(datetime::day_of_week::DateTimeDayOfWeek::new()))
		.register_builtin_function(Arc::new(datetime::quarter::DateTimeQuarter::new()))
		.register_builtin_function(Arc::new(datetime::week::DateTimeWeek::new()))
		.register_builtin_function(Arc::new(datetime::date::DateTimeDate::new()))
		.register_builtin_function(Arc::new(datetime::time::DateTimeTime::new()))
		.register_builtin_function(Arc::new(datetime::epoch::DateTimeEpoch::new()))
		.register_builtin_function(Arc::new(datetime::epoch_millis::DateTimeEpochMillis::new()))
		.register_builtin_function(Arc::new(datetime::new::DateTimeNew::new()))
		.register_builtin_function(Arc::new(datetime::now::DateTimeNow::new()))
		.register_builtin_function(Arc::new(datetime::from_epoch::DateTimeFromEpoch::new()))
		.register_builtin_function(Arc::new(datetime::from_epoch_millis::DateTimeFromEpochMillis::new()))
		.register_builtin_function(Arc::new(datetime::add::DateTimeAdd::new()))
		.register_builtin_function(Arc::new(datetime::subtract::DateTimeSubtract::new()))
		.register_builtin_function(Arc::new(datetime::diff::DateTimeDiff::new()))
		.register_builtin_function(Arc::new(datetime::trunc::DateTimeTrunc::new()))
		.register_builtin_function(Arc::new(datetime::age::DateTimeAge::new()))
		.register_builtin_function(Arc::new(datetime::format::DateTimeFormat::new()))
		.register_builtin_function(Arc::new(duration::years::DurationYears::new()))
		.register_builtin_function(Arc::new(duration::months::DurationMonths::new()))
		.register_builtin_function(Arc::new(duration::weeks::DurationWeeks::new()))
		.register_builtin_function(Arc::new(duration::days::DurationDays::new()))
		.register_builtin_function(Arc::new(duration::hours::DurationHours::new()))
		.register_builtin_function(Arc::new(duration::minutes::DurationMinutes::new()))
		.register_builtin_function(Arc::new(duration::seconds::DurationSeconds::new()))
		.register_builtin_function(Arc::new(duration::millis::DurationMillis::new()))
		.register_builtin_function(Arc::new(duration::get_months::DurationGetMonths::new()))
		.register_builtin_function(Arc::new(duration::get_days::DurationGetDays::new()))
		.register_builtin_function(Arc::new(duration::get_nanos::DurationGetNanos::new()))
		.register_builtin_function(Arc::new(duration::add::DurationAdd::new()))
		.register_builtin_function(Arc::new(duration::subtract::DurationSubtract::new()))
		.register_builtin_function(Arc::new(duration::negate::DurationNegate::new()))
		.register_builtin_function(Arc::new(duration::scale::DurationScale::new()))
		.register_builtin_function(Arc::new(duration::trunc::DurationTrunc::new()))
		.register_builtin_function(Arc::new(duration::format::DurationFormat::new()))
		.register_builtin_function_alias("duration::year", "duration::years")
		.register_builtin_function_alias("duration::month", "duration::months")
		.register_builtin_function_alias("duration::week", "duration::weeks")
		.register_builtin_function_alias("duration::day", "duration::days")
		.register_builtin_function_alias("duration::hour", "duration::hours")
		.register_builtin_function_alias("duration::minute", "duration::minutes")
		.register_builtin_function_alias("duration::second", "duration::seconds")
		.register_builtin_function(Arc::new(text::ascii::TextAscii::new()))
		.register_builtin_function(Arc::new(text::char::TextChar::new()))
		.register_builtin_function(Arc::new(text::concat::TextConcat::new()))
		.register_builtin_function(Arc::new(text::contains::TextContains::new()))
		.register_builtin_function(Arc::new(text::count::TextCount::new()))
		.register_builtin_function(Arc::new(text::ends_with::TextEndsWith::new()))
		.register_builtin_function(Arc::new(text::index_of::TextIndexOf::new()))
		.register_builtin_function(Arc::new(text::pad_left::TextPadLeft::new()))
		.register_builtin_function(Arc::new(text::pad_right::TextPadRight::new()))
		.register_builtin_function(Arc::new(text::repeat::TextRepeat::new()))
		.register_builtin_function(Arc::new(text::replace::TextReplace::new()))
		.register_builtin_function(Arc::new(text::reverse::TextReverse::new()))
		.register_builtin_function(Arc::new(text::starts_with::TextStartsWith::new()))
		.register_builtin_function(Arc::new(text::length::TextLength::new()))
		.register_builtin_function(Arc::new(text::trim::TextTrim::new()))
		.register_builtin_function(Arc::new(text::trim_end::TextTrimEnd::new()))
		.register_builtin_function(Arc::new(text::trim_start::TextTrimStart::new()))
		.register_builtin_function(Arc::new(text::upper::TextUpper::new()))
		.register_builtin_function(Arc::new(text::lower::TextLower::new()))
		.register_builtin_function(Arc::new(text::substring::TextSubstring::new()))
		.register_builtin_function(Arc::new(text::format_bytes::FormatBytes::new()))
		.register_builtin_function(Arc::new(text::format_bytes_si::FormatBytesSi::new()))
		.register_builtin_function(Arc::new(meta::r#type::Type::new()))
		.register_builtin_function(Arc::new(identity::id::Id::new()))
		.register_builtin_function(Arc::new(is::some::IsSome::new()))
		.register_builtin_function(Arc::new(is::none::IsNone::new()))
		.register_builtin_function(Arc::new(is::r#type::IsType::new()))
		.register_builtin_function(Arc::new(is::root::IsRoot::new()))
		.register_builtin_function(Arc::new(is::anonymous::IsAnonymous::new()))
		.register_builtin_function(Arc::new(json::object::JsonObject::new()))
		.register_builtin_function(Arc::new(json::array::JsonArray::new()))
		.register_builtin_function(Arc::new(json::pretty::JsonPretty::new()))
		.register_builtin_function(Arc::new(json::serialize::JsonSerialize::new()))
		.register_builtin_function(Arc::new(UuidV4::new()))
		.register_builtin_function(Arc::new(UuidV7::new()))
		.register_builtin_function(Arc::new(series::Series::new()))
		.register_builtin_function(Arc::new(series::GenerateSeries::new()))
		.register_builtin_function(Arc::new(rql::fingerprint::RqlFingerprint::new()))
}
