[package]
name = "regression"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
reifydb = { workspace = true, features = ["server", "client", "embedded_async", "embedded_sync"] }
reifydb-testing = { workspace = true }
test_each_file = { workspace = true }
tokio = { workspace = true }