[package]
name = "regression"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
reifydb = { workspace = true, features = ["sub_grpc", "sub_ws"] }
reifydb-network = { workspace = true, features = ["client", "websocket", "grpc"]}
reifydb-testing = { workspace = true }
test_each_file = { workspace = true }
tokio = { workspace = true }