packages:
  - auth
  - auth-solana
  - core
  - client
  - editor
  - react
  - reifydb
  - shell
  - store
  - ui
  - wasm

allowBuilds:
  '@swc/core': true
  bufferutil: true
  esbuild: true
  utf-8-validate: true

overrides:
  '@reifydb/core': link:core
