[package]
name = "reifydb-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-testing = { workspace = true }

crossbeam-skiplist = { workspace = true }

heed = { workspace = true }

rusqlite = { workspace = true, features = ["bundled"] }
r2d2 = { workspace = true }
r2d2_sqlite = { workspace = true }


[dev-dependencies]
test_each_file = { workspace = true }
