[package]
name = "reifydb-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "SDK for building ReifyDB operators, procedures, transforms and more"

[features]
default = ["host"]
host = [
    "dep:reifydb-codec",
    "dep:reifydb-flow",
    "dep:bumpalo",
    "dep:reifydb-core",
    "dep:reifydb-runtime",
    "dep:reifydb-value",
    "dep:postcard",
    "dep:rand",
    "dep:serde",
    "dep:reifydb-macro",
    "dep:tracing",
    "dep:uuid",
]

[build-dependencies]
reifydb-build = { workspace = true }

[dependencies]
reifydb-codec = { workspace = true, optional = true }
reifydb-flow = { workspace = true, optional = true }
bumpalo = { workspace = true, optional = true }
reifydb-core = { workspace = true, optional = true }
reifydb-runtime = { workspace = true, optional = true }
reifydb-value = { workspace = true, optional = true }
postcard = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
reifydb-macro = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[dev-dependencies]
reifydb-testing-sdk = { workspace = true }

[[test]]
name = "extern_c"
path = "tests/extern_c.rs"


