[package]
name = "reifydb-store-row"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-testing = { workspace = true }
reifydb-type = { workspace = true }

crossbeam-skiplist = { workspace = true }

rusqlite = { workspace = true, features = ["bundled"] }


[dev-dependencies]
test_each_file = { workspace = true }
reifydb-testing = { workspace = true}