[package]
name = "reifydb-sub-admin"
version = "0.0.1"
edition = "2024"
license = "AGPL-3"
authors = ["Dominique Chuo <dominique@reifydb.com>"]

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-type = { workspace = true }
reifydb-network = { workspace = true }

mio = { workspace = true }
slab = { workspace = true }
socket2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]