[package]
name = "reifydb-sub-log"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
reifydb-core = { workspace = true }

# For structured logging
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Performance
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true, features = ["serde"] }

# For colored console output
colored = { workspace = true }
