// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 ReifyDB

//! In-memory session token store with TTL-based expiry.

use std::{
	collections::HashMap,
	sync::RwLock,
	time::{Duration, Instant},
};

use reifydb_core::interface::catalog::user::UserId;
use reifydb_type::value::identity::IdentityId;

use crate::crypto::constant_time_eq;

/// Entry for an active session token.
struct SessionEntry {
	identity: IdentityId,
	user_id: UserId,
	token: String,
	expires_at: Option<Instant>,
}

/// In-memory store for active session tokens.
///
/// Tokens are stored keyed by a random ID and validated via constant-time
/// comparison. Expired entries are lazily cleaned up on access.
pub struct SessionStore {
	entries: RwLock<HashMap<String, SessionEntry>>,
	default_ttl: Option<Duration>,
}

/// Information about an active session.
#[derive(Debug, Clone)]
pub struct SessionInfo {
	pub identity: IdentityId,
	pub user_id: UserId,
}

impl SessionStore {
	pub fn new(default_ttl: Option<Duration>) -> Self {
		Self {
			entries: RwLock::new(HashMap::new()),
			default_ttl,
		}
	}

	/// Store a session token and return it.
	/// The token itself is generated by the caller.
	pub fn insert(&self, token: String, identity: IdentityId, user_id: UserId) -> String {
		let expires_at = self.default_ttl.map(|ttl| Instant::now() + ttl);
		let entry = SessionEntry {
			identity,
			user_id,
			token: token.clone(),
			expires_at,
		};
		let mut entries = self.entries.write().unwrap();
		entries.insert(token.clone(), entry);
		token
	}

	/// Validate a token and return the associated session info.
	/// Returns `None` if the token is not found or has expired.
	pub fn validate(&self, token: &str) -> Option<SessionInfo> {
		let entries = self.entries.read().unwrap();
		for entry in entries.values() {
			if constant_time_eq(entry.token.as_bytes(), token.as_bytes()) {
				if let Some(expires_at) = entry.expires_at {
					if Instant::now() > expires_at {
						return None;
					}
				}
				return Some(SessionInfo {
					identity: entry.identity,
					user_id: entry.user_id,
				});
			}
		}
		None
	}

	/// Revoke a specific session token.
	/// Returns `true` if the token was found and removed.
	pub fn revoke(&self, token: &str) -> bool {
		let mut entries = self.entries.write().unwrap();
		// Find key by constant-time comparison
		let key = entries
			.iter()
			.find(|(_, e)| constant_time_eq(e.token.as_bytes(), token.as_bytes()))
			.map(|(k, _)| k.clone());
		if let Some(key) = key {
			entries.remove(&key);
			true
		} else {
			false
		}
	}

	/// Revoke all session tokens for a given identity.
	pub fn revoke_all(&self, identity: IdentityId) {
		let mut entries = self.entries.write().unwrap();
		entries.retain(|_, e| e.identity != identity);
	}

	/// Remove all expired entries. Called periodically or lazily.
	pub fn cleanup_expired(&self) {
		let now = Instant::now();
		let mut entries = self.entries.write().unwrap();
		entries.retain(|_, e| e.expires_at.map_or(true, |exp| now <= exp));
	}
}

#[cfg(test)]
mod tests {
	use std::thread;

	use super::*;

	#[test]
	fn test_insert_and_validate() {
		let store = SessionStore::new(None);
		let identity = IdentityId::generate();
		let user_id = 1;

		let token = store.insert("test-token-123".to_string(), identity, user_id);
		let info = store.validate(&token).unwrap();
		assert_eq!(info.identity, identity);
		assert_eq!(info.user_id, user_id);
	}

	#[test]
	fn test_validate_unknown_token() {
		let store = SessionStore::new(None);
		assert!(store.validate("nonexistent").is_none());
	}

	#[test]
	fn test_revoke() {
		let store = SessionStore::new(None);
		let identity = IdentityId::generate();
		let token = store.insert("tok".to_string(), identity, 1);

		assert!(store.validate(&token).is_some());
		assert!(store.revoke(&token));
		assert!(store.validate(&token).is_none());
	}

	#[test]
	fn test_revoke_all() {
		let store = SessionStore::new(None);
		let identity = IdentityId::generate();
		let t1 = store.insert("tok1".to_string(), identity, 1);
		let t2 = store.insert("tok2".to_string(), identity, 1);

		let other_identity = IdentityId::generate();
		let t3 = store.insert("tok3".to_string(), other_identity, 2);

		store.revoke_all(identity);
		assert!(store.validate(&t1).is_none());
		assert!(store.validate(&t2).is_none());
		assert!(store.validate(&t3).is_some());
	}

	#[test]
	fn test_expiry() {
		let store = SessionStore::new(Some(Duration::from_millis(1)));
		let identity = IdentityId::generate();
		let token = store.insert("tok".to_string(), identity, 1);

		// Wait for expiry
		thread::sleep(Duration::from_millis(10));
		assert!(store.validate(&token).is_none());
	}
}
