[package]
name = "reifydb-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }

[dev-dependencies]
test_each_file = { workspace = true }