[package]
name = "bench"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "reifydb_bench"
path = "src/lib.rs"

[dependencies]
reifydb = { path = "../../pkg/rust/reifydb", features = ["sub_server", "sub_logging"] }
reifydb-rql = { path = "../../crates/reifydb-rql" }
reifydb-sub-server = { path = "../../crates/reifydb-sub-server" }

tokio = { workspace = true, features = ["time"] }

criterion = { workspace = true }
tokio-tungstenite = "0.27"
futures-util = "0.3"
serde_json = { workspace = true}

[[bench]]
name = "engine-memory-optimistic"
path = "benches/engine/01_memory_optimistic.rs"
harness = false

[[bench]]
name = "rql-tokenize"
path = "benches/rql/tokenize.rs"
harness = false

[[bench]]
name = "rql-parse"
path = "benches/rql/parse.rs"
harness = false

[[bench]]
name = "rql-logical"
path = "benches/rql/logical.rs"
harness = false

[[bench]]
name = "ws-server"
path = "benches/server/ws.rs"
harness = false