[package]
name = "reifydb-sub-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-type = { workspace = true }

[dev-dependencies]
reifydb-catalog = { workspace = true }
reifydb-store-transaction = { workspace = true }
reifydb-transaction = { workspace = true }
reifydb-cdc = { workspace = true }
