[package]
name = "reifydb-transaction"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
test-stress = []
worker_pool = []

[dependencies]
reifydb-core = { workspace = true }
reifydb-storage = { workspace = true }

crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }


[dev-dependencies]
reifydb-testing = { workspace = true }
reifydb-engine = { workspace = true }
test_each_file = { workspace = true }
