// Copyright (c) reifydb.com 2025
// This file is licensed under the AGPL-3.0-or-later, see license.md file

//! User-facing API for defining virtual tables.
//!
//! This module provides simplified traits for users to implement custom virtual tables.
//! Users can choose between two levels of abstraction:
//!
//! - [`TableVirtualUser`]: Simple API for tables that can return all rows at once
//! - [`TableVirtualUserIterator`]: Advanced API for streaming large datasets with optional pushdown
//!
//! # Example
//!
//! ```ignore
//! use reifydb_engine::table_virtual::{TableVirtualUser, TableVirtualUserColumnDef};
//! use reifydb_type::Type;
//! use reifydb_core::value::Value;
//!
//! struct MyApiTable {
//!     api_client: ApiClient,
//! }
//!
//! impl TableVirtualUser for MyApiTable {
//!     fn columns(&self) -> Vec<TableVirtualUserColumnDef> {
//!         vec![
//!             TableVirtualUserColumnDef::new("id", Type::Uint8),
//!             TableVirtualUserColumnDef::new("name", Type::Utf8),
//!         ]
//!     }
//!
//!     fn rows(&self) -> Vec<Vec<Value>> {
//!         self.api_client.fetch_data()
//!             .map(|r| vec![Value::Uint8(r.id), Value::Utf8(r.name.into())])
//!             .collect()
//!     }
//! }
//! ```

use async_trait::async_trait;
use reifydb_type::{Type, Value};

/// Column definition for user virtual tables.
#[derive(Debug, Clone)]
pub struct TableVirtualUserColumnDef {
	/// Column name
	pub name: String,
	/// Column data type
	pub data_type: Type,
	/// Whether the column allows null values
	pub nullable: bool,
}

impl TableVirtualUserColumnDef {
	/// Create a new non-nullable column definition.
	pub fn new(name: impl Into<String>, data_type: Type) -> Self {
		Self {
			name: name.into(),
			data_type,
			nullable: false,
		}
	}

	/// Create a new nullable column definition.
	pub fn nullable(name: impl Into<String>, data_type: Type) -> Self {
		Self {
			name: name.into(),
			data_type,
			nullable: true,
		}
	}
}

/// Simple trait for user-defined virtual tables.
///
/// Implement this trait when your virtual table can return all rows at once.
/// For large datasets that should be streamed, implement [`TableVirtualUserIterator`] instead.
///
/// # Thread Safety
///
/// Implementations must be thread-safe (`Send + Sync`) as the same table instance
/// may be queried concurrently from multiple transactions.
pub trait TableVirtualUser: Send + Sync + 'static {
	/// Return the column definitions for this table.
	fn columns(&self) -> Vec<TableVirtualUserColumnDef>;

	/// Generate all rows for the table.
	///
	/// Each inner `Vec<Value>` represents one row, with values in the same order
	/// as the columns returned by [`columns()`](Self::columns).
	fn rows(&self) -> Vec<Vec<Value>>;
}

/// Pushdown context for advanced virtual table implementations.
///
/// Contains optimization hints that can be used to reduce the amount of data
/// generated by the virtual table.
#[derive(Debug, Clone, Default)]
pub struct TableVirtualUserPushdownContext {
	/// Maximum number of rows to return (if set).
	pub limit: Option<usize>,
	// Future: filters, projections, etc.
}

/// Advanced trait for streaming virtual table implementations.
///
/// Implement this trait when your virtual table needs to:
/// - Stream large datasets in batches
/// - Take advantage of pushdown optimizations (limit, filters)
///
/// # Thread Safety
///
/// Unlike [`TableVirtualUser`], implementations of this trait are instantiated
/// fresh for each query. The factory creates a new instance per query execution.
#[async_trait]
pub trait TableVirtualUserIterator: Send + Sync + 'static {
	/// Return the column definitions for this table.
	fn columns(&self) -> Vec<TableVirtualUserColumnDef>;

	/// Initialize the iterator with optional pushdown context.
	///
	/// Called once before iteration begins. Use the pushdown context to
	/// optimize data generation (e.g., limit the number of rows fetched).
	async fn initialize(&mut self, ctx: Option<&TableVirtualUserPushdownContext>) -> crate::Result<()>;

	/// Get the next batch of rows.
	///
	/// Returns `Ok(Some(rows))` with the next batch, or `Ok(None)` when exhausted.
	/// Each inner `Vec<Value>` represents one row.
	///
	/// The `batch_size` parameter is a hint for how many rows to return.
	async fn next_batch(&mut self, batch_size: usize) -> crate::Result<Option<Vec<Vec<Value>>>>;
}
