// Copyright (c) reifydb.com 2025
// This file is licensed under the AGPL-3.0-or-later

use regex::Regex;
use reifydb_core::AsyncCowVec;
use reifydb_core::encoding::binary::decode_binary;
use std::collections::Bound;
use std::ops::RangeBounds;

pub type Key = AsyncCowVec<u8>;

#[derive(Clone, Debug)]
pub struct KeyRange {
    pub(crate) start: Bound<Key>,
    pub(crate) end: Bound<Key>,
}

impl KeyRange {
    /// Generates a key range for a key prefix, used e.g. for prefix scans.
    ///
    /// The exclusive end bound is generated by adding 1 to the value of the last
    /// byte. If the last byte(s) is 0xff (so adding 1 would saturation), we instead
    /// find the latest non-0xff byte, increment that, and truncate the rest. If all
    /// bytes are 0xff, we scan to the end of the range, since there can't be other
    /// prefixes after it.
    pub fn prefix(prefix: &[u8]) -> Self {
        let start = Bound::Included(AsyncCowVec::new(prefix.to_vec()));
        let end = match prefix.iter().rposition(|&b| b != 0xff) {
            Some(i) => Bound::Excluded(AsyncCowVec::new(
                prefix.iter().take(i).copied().chain(std::iter::once(prefix[i] + 1)).collect(),
            )),
            None => Bound::Unbounded,
        };
        Self { start, end }
    }

    /// Constructs a key range from an optional inclusive start key to an optional exclusive end key.
    ///
    /// - `start`: If provided, marks the inclusive lower bound of the range. If `None`, the range is unbounded below.
    /// - `end`: If provided, marks the exclusive upper bound of the range. If `None`, the range is unbounded above.
    ///
    /// This function does not modify the input keys and assumes they are already exact keys
    /// (not prefixes). If you need to scan all keys with a given prefix, use [`KeyRange::prefix`] instead.
    ///
    /// Useful for scanning between two explicit keys in a sorted key-value store.
    pub fn start_end(start: Option<Key>, end: Option<Key>) -> Self {
        let start = match start {
            Some(s) => Bound::Included(s),
            None => Bound::Unbounded,
        };

        let end = match end {
            Some(e) => Bound::Excluded(e),
            None => Bound::Unbounded,
        };

        Self { start, end }
    }

    /// Constructs a key range that spans the entire keyspace.
    ///
    /// This range has no lower or upper bounds, making it suitable for full scans
    /// over all keys in a sorted key-value store.
    ///
    /// Equivalent to: `..` (in Rust range syntax)
    pub fn all() -> Self {
        Self { start: Bound::Unbounded, end: Bound::Unbounded }
    }

    /// Parses a human-readable range string into a `KeyRange`.
    ///
    /// The expected format is `<start>..[=]<end>`, where:
    /// - `<start>` is the inclusive lower bound (optional),
    /// - `..` separates the bounds,
    /// - `=` after `..` makes the upper bound inclusive,
    /// - `<end>` is the upper bound (optional).
    ///
    /// Examples:
    /// - `"a..z"`       => start = Included("a"), end = Excluded("z")
    /// - `"a..=z"`      => start = Included("a"), end = Included("z")
    /// - `"..z"`        => start = Unbounded,     end = Excluded("z")
    /// - `"a.."`        => start = Included("a"), end = Unbounded
    ///
    /// If parsing fails, it defaults to a degenerate range from `0xff` to `0xff` (empty).
    pub fn parse(str: &str) -> Self {
        let (mut start, mut end) =
            (Bound::<AsyncCowVec<u8>>::Unbounded, Bound::<AsyncCowVec<u8>>::Unbounded);

        let re = Regex::new(r"^(\S+)?\.\.(=)?(\S+)?").expect("invalid regex");

        re.captures(str)
            .map(|groups| {
                if let Some(m) = groups.get(1) {
                    start = Bound::Included(decode_binary(m.as_str()));
                }
                if let Some(m) = groups.get(3) {
                    let decoded = decode_binary(m.as_str());
                    if groups.get(2).is_some() {
                        end = Bound::Included(decoded)
                    } else {
                        end = Bound::Excluded(decoded)
                    }
                }
                Self { start, end }
            })
            .unwrap_or(Self {
                start: Bound::Included(AsyncCowVec::new(vec![0xff])),
                end: Bound::Excluded(AsyncCowVec::new(vec![0xff])),
            })
    }
}

impl RangeBounds<Key> for KeyRange {
    fn start_bound(&self) -> Bound<&Key> {
        self.start.as_ref()
    }

    fn end_bound(&self) -> Bound<&Key> {
        self.end.as_ref()
    }
}

#[cfg(test)]
mod tests {
    use reifydb_core::AsyncCowVec;
    use std::collections::Bound;

    macro_rules! as_key {
        ($key:expr) => {{ AsyncCowVec::new(keycode::serialize(&$key)) }};
    }

    mod prefix {
        use crate::KeyRange;
        use crate::key::tests::{excluded, included};
        use std::ops::Bound;

        #[test]
        fn test_simple() {
            let range = KeyRange::prefix(&[0x12, 0x34]);
            assert_eq!(range.start, included(&[0x12, 0x34]));
            assert_eq!(range.end, excluded(&[0x12, 0x35]));
        }

        #[test]
        fn test_with_trailing_ff() {
            let range = KeyRange::prefix(&[0x12, 0xff]);
            assert_eq!(range.start, included(&[0x12, 0xff]));
            assert_eq!(range.end, excluded(&[0x13]));
        }

        #[test]
        fn test_with_multiple_trailing_ff() {
            let range = KeyRange::prefix(&[0x12, 0xff, 0xff]);
            assert_eq!(range.start, included(&[0x12, 0xff, 0xff]));
            assert_eq!(range.end, excluded(&[0x13]));
        }

        #[test]
        fn test_all_ff() {
            let range = KeyRange::prefix(&[0xff, 0xff]);
            assert_eq!(range.start, included(&[0xff, 0xff]));
            assert_eq!(range.end, Bound::Unbounded);
        }

        #[test]
        fn test_empty() {
            let range = KeyRange::prefix(&[]);
            assert_eq!(range.start, included(&[]));
            assert_eq!(range.end, Bound::Unbounded);
        }

        #[test]
        fn test_mid_increment() {
            let range = KeyRange::prefix(&[0x12, 0x00, 0xff]);
            assert_eq!(range.start, included(&[0x12, 0x00, 0xff]));
            assert_eq!(range.end, excluded(&[0x12, 0x01]));
        }
    }

    mod start_end {
        use crate::KeyRange;
        use crate::key::AsyncCowVec;
        use crate::key::tests::{excluded, included};
        use reifydb_core::encoding::keycode;
        use std::ops::Bound;

        #[test]
        fn test_start_and_end() {
            let range = KeyRange::start_end(Some(as_key!(1)), Some(as_key!(2)));
            assert_eq!(range.start, included(&as_key!(1)));
            assert_eq!(range.end, excluded(&as_key!(2)));
        }

        #[test]
        fn test_start_only() {
            let range = KeyRange::start_end(Some(as_key!(1)), None);
            assert_eq!(range.start, included(&as_key!(1)));
            assert_eq!(range.end, Bound::Unbounded);
        }

        #[test]
        fn test_end_only() {
            let range = KeyRange::start_end(None, Some(as_key!(2)));
            assert_eq!(range.start, Bound::Unbounded);
            assert_eq!(range.end, excluded(&as_key!(2)));
        }

        #[test]
        fn test_unbounded_range() {
            let range = KeyRange::start_end(None, None);
            assert_eq!(range.start, Bound::Unbounded);
            assert_eq!(range.end, Bound::Unbounded);
        }

        #[test]
        fn test_full_byte_range() {
            let range = KeyRange::start_end(Some(as_key!(0x00)), Some(as_key!(0xff)));
            assert_eq!(range.start, included(&as_key!(0x00)));
            assert_eq!(range.end, excluded(&as_key!(0xff)));
        }

        #[test]
        fn test_identical_bounds() {
            let range = KeyRange::start_end(Some(as_key!(0x42)), Some(as_key!(0x42)));
            assert_eq!(range.start, included(&as_key!(0x42)));
            assert_eq!(range.end, excluded(&as_key!(0x42)));
        }
    }

    mod all {
        use crate::KeyRange;
        use std::ops::Bound;

        #[test]
        fn test_is_unbounded() {
            let range = KeyRange::all();
            assert_eq!(range.start, Bound::Unbounded);
            assert_eq!(range.end, Bound::Unbounded);
        }
    }

    mod parse {
        use crate::KeyRange;
        use crate::key::tests::{excluded, included};
        use reifydb_core::AsyncCowVec;
        use std::ops::Bound;

        #[test]
        fn test_full_range() {
            let r = KeyRange::parse("a..z");
            assert_eq!(r.start, included(b"a"));
            assert_eq!(r.end, excluded(b"z"));
        }

        #[test]
        fn test_inclusive_end() {
            let r = KeyRange::parse("a..=z");
            assert_eq!(r.start, included(b"a"));
            assert_eq!(r.end, included(b"z"));
        }

        #[test]
        fn test_unbounded_start() {
            let r = KeyRange::parse("..z");
            assert_eq!(r.start, Bound::Unbounded);
            assert_eq!(r.end, excluded(b"z"));
        }

        #[test]
        fn test_unbounded_end() {
            let r = KeyRange::parse("a..");
            assert_eq!(r.start, included(b"a"));
            assert_eq!(r.end, Bound::Unbounded);
        }

        #[test]
        fn test_inclusive_only() {
            let r = KeyRange::parse("..=z");
            assert_eq!(r.start, Bound::Unbounded);
            assert_eq!(r.end, included(b"z"));
        }

        #[test]
        fn test_invalid_string_returns_degenerate_range() {
            let r = KeyRange::parse("not a range");
            let expected = AsyncCowVec::new(vec![0xff]);
            assert_eq!(r.start, Bound::Included(expected.clone()));
            assert_eq!(r.end, Bound::Excluded(expected));
        }

        #[test]
        fn test__empty_string_returns_degenerate_range() {
            let r = KeyRange::parse("");
            let expected = AsyncCowVec::new(vec![0xff]);
            assert_eq!(r.start, Bound::Included(expected.clone()));
            assert_eq!(r.end, Bound::Excluded(expected));
        }

        #[test]
        fn test_binary_encoded_values() {
            let r = KeyRange::parse("0101..=0aff");
            // decode_binary("0101") = [0x01, 0x01]
            assert_eq!(r.start, included(b"0101"));
            // decode_binary("0aff") = [0x0a, 0xff]
            assert_eq!(r.end, included(b"0aff"));
        }
    }

    fn included(bytes: &[u8]) -> Bound<AsyncCowVec<u8>> {
        Bound::Included(AsyncCowVec::new(bytes.to_vec()))
    }

    fn excluded(bytes: &[u8]) -> Bound<AsyncCowVec<u8>> {
        Bound::Excluded(AsyncCowVec::new(bytes.to_vec()))
    }
}
