[package]
name = "reifydb-sub-console"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Console subsystem for ReifyDB"

[features]
default = []

[dependencies]
yamux = { workspace = true }

[build-dependencies]
reifydb-build = { workspace = true }
