[package]
name = "reifydb-sub-console"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Console subsystem for ReifyDB"

[features]
default = []

[dependencies]
reifydb-console-protocol = { workspace = true }
reifydb-core = { workspace = true }
reifydb-runtime = { workspace = true }
reifydb-sub-api = { workspace = true }
reifydb-sub-server-ws = { workspace = true }
reifydb-value = { workspace = true }

socket2 = { workspace = true }
tokio = { workspace = true, features = ["net", "time", "macros", "sync", "rt"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
yamux = { workspace = true }

[build-dependencies]
reifydb-build = { workspace = true }
