[package]
name = "reifydb-cdc"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }

[dev-dependencies]
reifydb-storage = { workspace = true }
reifydb-transaction = { workspace = true }