[package]
name = "reifydb-flow"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-core = { workspace = true }
reifydb-catalog = { workspace = true }
reifydb-rql = { workspace = true }
reifydb-storage = { workspace = true }
reifydb-transaction = { workspace = true }

serde = { workspace = true }

[dev-dependencies]
reifydb-testing = { workspace = true }
reifydb = {workspace = true, features = ["sub_flow"]}
test_each_file = { workspace = true }