[package]
name = "reifydb-engine"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb-auth = { workspace = true }
reifydb-catalog = { workspace = true }
reifydb-core = { workspace = true }
reifydb-rql = { workspace = true }
reifydb-storage = { workspace = true }
reifydb-transaction = { workspace = true }

once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unicode-width = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
reifydb-testing = { workspace = true }

[[example]]
name = "flow_subsystem_demo"
path = "examples/flow_subsystem_demo.rs"