[package]
name = "reifydb_frame"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reifydb_core = { workspace = true }

[dev-dependencies]
rand = {workspace = true}