// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 ReifyDB

use reifydb_core::{
	encoded::key::EncodedKey,
	key::{Key, kind::KeyKind},
};

pub(crate) enum ReadFrom {
	StateQuery,

	Query,
}

pub(crate) fn read_from(key: &EncodedKey) -> ReadFrom {
	match Key::kind(key) {
		None => ReadFrom::Query,
		Some(kind) => match kind {
			KeyKind::FlowNodeState => ReadFrom::StateQuery,
			KeyKind::FlowNodeInternalState => ReadFrom::StateQuery,
			KeyKind::RingBufferMetadata => ReadFrom::StateQuery,
			KeyKind::SeriesMetadata => ReadFrom::StateQuery,

			KeyKind::Row => ReadFrom::Query,

			KeyKind::Namespace => ReadFrom::Query,
			KeyKind::Table => ReadFrom::Query,
			KeyKind::NamespaceTable => ReadFrom::Query,
			KeyKind::SystemSequence => ReadFrom::Query,
			KeyKind::Columns => ReadFrom::Query,
			KeyKind::Column => ReadFrom::Query,
			KeyKind::RowSequence => ReadFrom::Query,
			KeyKind::ColumnProperty => ReadFrom::Query,
			KeyKind::SystemVersion => ReadFrom::Query,
			KeyKind::TransactionVersion => ReadFrom::Query,
			KeyKind::Index => ReadFrom::Query,
			KeyKind::IndexEntry => ReadFrom::Query,
			KeyKind::ColumnSequence => ReadFrom::Query,
			KeyKind::CdcConsumer => ReadFrom::Query,
			KeyKind::View => ReadFrom::Query,
			KeyKind::NamespaceView => ReadFrom::Query,
			KeyKind::PrimaryKey => ReadFrom::Query,
			KeyKind::RingBuffer => ReadFrom::Query,
			KeyKind::NamespaceRingBuffer => ReadFrom::Query,
			KeyKind::ShapeRetentionStrategy => ReadFrom::Query,
			KeyKind::OperatorRetentionStrategy => ReadFrom::Query,
			KeyKind::Flow => ReadFrom::Query,
			KeyKind::NamespaceFlow => ReadFrom::Query,
			KeyKind::FlowNode => ReadFrom::Query,
			KeyKind::FlowNodeByFlow => ReadFrom::Query,
			KeyKind::FlowEdge => ReadFrom::Query,
			KeyKind::FlowEdgeByFlow => ReadFrom::Query,
			KeyKind::Dictionary => ReadFrom::Query,
			KeyKind::DictionaryEntry => ReadFrom::Query,
			KeyKind::DictionaryEntryIndex => ReadFrom::Query,
			KeyKind::NamespaceDictionary => ReadFrom::Query,
			KeyKind::Metric => ReadFrom::Query,
			KeyKind::FlowVersion => ReadFrom::Query,
			KeyKind::Subscription => ReadFrom::Query,
			KeyKind::SubscriptionRow => ReadFrom::Query,
			KeyKind::SubscriptionColumn => ReadFrom::Query,
			KeyKind::Shape => ReadFrom::Query,
			KeyKind::RowShapeField => ReadFrom::Query,
			KeyKind::SumType => ReadFrom::Query,
			KeyKind::NamespaceSumType => ReadFrom::Query,
			KeyKind::Handler => ReadFrom::Query,
			KeyKind::NamespaceHandler => ReadFrom::Query,
			KeyKind::VariantHandler => ReadFrom::Query,
			KeyKind::Series => ReadFrom::Query,
			KeyKind::NamespaceSeries => ReadFrom::Query,
			KeyKind::Identity => ReadFrom::Query,
			KeyKind::Role => ReadFrom::Query,
			KeyKind::GrantedRole => ReadFrom::Query,
			KeyKind::Policy => ReadFrom::Query,
			KeyKind::PolicyOp => ReadFrom::Query,
			KeyKind::Migration => ReadFrom::Query,
			KeyKind::MigrationEvent => ReadFrom::Query,
			KeyKind::Authentication => ReadFrom::Query,
			KeyKind::ConfigStorage => ReadFrom::Query,
			KeyKind::Token => ReadFrom::Query,
			KeyKind::Source => ReadFrom::Query,
			KeyKind::NamespaceSource => ReadFrom::Query,
			KeyKind::Sink => ReadFrom::Query,
			KeyKind::NamespaceSink => ReadFrom::Query,
			KeyKind::SourceCheckpoint => ReadFrom::Query,
			KeyKind::RowSettings => ReadFrom::Query,
			KeyKind::OperatorSettings => ReadFrom::Query,
			KeyKind::Procedure => ReadFrom::Query,
			KeyKind::NamespaceProcedure => ReadFrom::Query,
			KeyKind::ProcedureParam => ReadFrom::Query,
			KeyKind::Binding => ReadFrom::Query,
			KeyKind::NamespaceBinding => ReadFrom::Query,
			KeyKind::ColumnSnapshot => ReadFrom::Query,
			KeyKind::SeriesColumnSnapshot => ReadFrom::Query,
			KeyKind::TableColumnSnapshot => ReadFrom::Query,
		},
	}
}
