// Copyright (c) reifydb.com 2025
// This file is licensed under the AGPL-3.0-or-later, see license.md file

//! Auto-generated test modules
//!
//! This file is generated by build.rs - DO NOT EDIT
//!
//! This file includes the auto-generated test modules created by the build
//! script. The tests are generated from the scripts in tests/scripts/
//! directory.

// Import the test functions from the other test files
// These are used by the generated tests
pub use cdc::{test_cdc_memory, test_cdc_sqlite};
pub use unversioned::{test_unversioned_memory, test_unversioned_sqlite};
pub use versioned::{test_versioned_memory, test_versioned_sqlite};

// Import the other test modules to access their public functions
mod cdc;
mod unversioned;
mod versioned;

// Include the generated test modules
pub mod generated;
