[package]
name = "smoke"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
reifydb = { workspace = true }
testing = { workspace = true }
test_each_file = { workspace = true }
