// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2025 ReifyDB

use reifydb_type::error::Error;
use serde::{Deserialize, Serialize};

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "u8", into = "u8")]
pub enum KeyKind {
	Namespace = 0x01,
	Table = 0x02,
	Row = 0x03,
	NamespaceTable = 0x04,
	SystemSequence = 0x05,
	Columns = 0x06,
	Column = 0x07,
	RowSequence = 0x08,
	ColumnPolicy = 0x09,
	SystemVersion = 0x0A,
	TransactionVersion = 0x0B,
	Index = 0x0C,
	IndexEntry = 0x0D,
	ColumnSequence = 0x0E,
	CdcConsumer = 0x0F,
	View = 0x10,
	NamespaceView = 0x11,
	PrimaryKey = 0x12,
	FlowNodeState = 0x13,
	RingBuffer = 0x14,
	NamespaceRingBuffer = 0x15,
	RingBufferMetadata = 0x16,
	PrimitiveRetentionPolicy = 0x17,
	OperatorRetentionPolicy = 0x18,
	Flow = 0x19,
	NamespaceFlow = 0x1A,
	FlowNode = 0x1B,
	FlowNodeByFlow = 0x1C,
	FlowEdge = 0x1D,
	FlowEdgeByFlow = 0x1E,
	FlowNodeInternalState = 0x1F,
	Dictionary = 0x20,
	DictionaryEntry = 0x21,
	DictionaryEntryIndex = 0x22,
	NamespaceDictionary = 0x23,
	DictionarySequence = 0x24,
	Metric = 0x25,
	FlowVersion = 0x26,
	Subscription = 0x27,
	SubscriptionRow = 0x28,
	SubscriptionColumn = 0x29,
	Schema = 0x2A,
	SchemaField = 0x2B,
	SumType = 0x2C,
	NamespaceSumType = 0x2D,
	Handler = 0x2E,
	NamespaceHandler = 0x2F,
	VariantHandler = 0x30,
	Series = 0x31,
	NamespaceSeries = 0x32,
	SeriesMetadata = 0x33,
	User = 0x34,
	Role = 0x35,
	UserRole = 0x36,
	SecurityPolicy = 0x37,
	SecurityPolicyOp = 0x38,
}

impl From<KeyKind> for u8 {
	fn from(kind: KeyKind) -> Self {
		kind as u8
	}
}
impl TryFrom<u8> for KeyKind {
	type Error = Error;

	fn try_from(value: u8) -> Result<Self, Self::Error> {
		match value {
			0x01 => Ok(Self::Namespace),
			0x02 => Ok(Self::Table),
			0x03 => Ok(Self::Row),
			0x04 => Ok(Self::NamespaceTable),
			0x05 => Ok(Self::SystemSequence),
			0x06 => Ok(Self::Columns),
			0x07 => Ok(Self::Column),
			0x08 => Ok(Self::RowSequence),
			0x09 => Ok(Self::ColumnPolicy),
			0x0A => Ok(Self::SystemVersion),
			0x0B => Ok(Self::TransactionVersion),
			0x0C => Ok(Self::Index),
			0x0D => Ok(Self::IndexEntry),
			0x0E => Ok(Self::ColumnSequence),
			0x0F => Ok(Self::CdcConsumer),
			0x10 => Ok(Self::View),
			0x11 => Ok(Self::NamespaceView),
			0x12 => Ok(Self::PrimaryKey),
			0x13 => Ok(Self::FlowNodeState),
			0x14 => Ok(Self::RingBuffer),
			0x15 => Ok(Self::NamespaceRingBuffer),
			0x16 => Ok(Self::RingBufferMetadata),
			0x17 => Ok(Self::PrimitiveRetentionPolicy),
			0x18 => Ok(Self::OperatorRetentionPolicy),
			0x19 => Ok(Self::Flow),
			0x1A => Ok(Self::NamespaceFlow),
			0x1B => Ok(Self::FlowNode),
			0x1C => Ok(Self::FlowNodeByFlow),
			0x1D => Ok(Self::FlowEdge),
			0x1E => Ok(Self::FlowEdgeByFlow),
			0x1F => Ok(Self::FlowNodeInternalState),
			0x20 => Ok(Self::Dictionary),
			0x21 => Ok(Self::DictionaryEntry),
			0x22 => Ok(Self::DictionaryEntryIndex),
			0x23 => Ok(Self::NamespaceDictionary),
			0x24 => Ok(Self::DictionarySequence),
			0x25 => Ok(Self::Metric),
			0x26 => Ok(Self::FlowVersion),
			0x27 => Ok(Self::Subscription),
			0x28 => Ok(Self::SubscriptionRow),
			0x29 => Ok(Self::SubscriptionColumn),
			0x2A => Ok(Self::Schema),
			0x2B => Ok(Self::SchemaField),
			0x2C => Ok(Self::SumType),
			0x2D => Ok(Self::NamespaceSumType),
			0x2E => Ok(Self::Handler),
			0x2F => Ok(Self::NamespaceHandler),
			0x30 => Ok(Self::VariantHandler),
			0x31 => Ok(Self::Series),
			0x32 => Ok(Self::NamespaceSeries),
			0x33 => Ok(Self::SeriesMetadata),
			0x34 => Ok(Self::User),
			0x35 => Ok(Self::Role),
			0x36 => Ok(Self::UserRole),
			0x37 => Ok(Self::SecurityPolicy),
			0x38 => Ok(Self::SecurityPolicyOp),
			_ => Err(serde::de::Error::custom(format!("Invalid KeyKind value: {value:#04x}"))),
		}
	}
}
