[package]
name = "reifydb-sub-server"
version = "0.0.1"
edition = "2024"
license = "AGPL-3"
authors = ["Dominique Chuo <dominique@reifydb.com>"]

[dependencies]
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }
reifydb-type = { workspace = true }
reifydb-hash = { workspace = true }

# Network and async dependencies
mio = { version = "1.0.4", features = ["net", "os-poll"] }
slab = "0.4"
socket2 = { version = "0.6", features = ["all"] }

# Utilities
num_cpus = "1.16"
core_affinity = "0.8"

# WebSocket protocol support  
httparse = "1.8"

# HTTP protocol support
urlencoding = "2.1"

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
reifydb-testing = { path = "../reifydb-testing", version = "0.0.1" }