[package]
name = "reifydb-sub-server"
version = "0.0.1"
edition = "2024"
license = "AGPL-3"
authors = ["Dominique Chuo <dominique@reifydb.com>"]

[dependencies]
# Core ReifyDB dependencies
reifydb-core = { path = "../reifydb-core", version = "0.0.1" }
reifydb-engine = { path = "../reifydb-engine", version = "0.0.1" }

# Network and async dependencies
mio = { version = "0.8", features = ["net", "os-poll"] }
slab = "0.4"
socket2 = { version = "0.5", features = ["all"] }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }

# Utilities
num_cpus = "1.16"
core_affinity = "0.8"

# WebSocket protocol support  
httparse = "1.8"
base64 = "0.22"
sha1 = "0.10"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
reifydb-testing = { path = "../reifydb-testing", version = "0.0.1" }