use std::env;

fn main() -> Result<(), Box<dyn std::error::Error>> {
	generate_tests()?;
	Ok(())
}

fn generate_tests() -> Result<(), Box<dyn std::error::Error>> {
	use reifydb_testing::test_generator::{
		TestConfig, TestGenerator, add_rerun_if_changed,
	};

	let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;

	// Add rerun directives
	add_rerun_if_changed("tests/scripts");
	add_rerun_if_changed("build.rs");

	let mut generators = Vec::new();

	// Create test generator
	let mut generator = TestGenerator::new(&manifest_dir, "generated")?;

	// Clean old generated files
	generator.clean()?;

	// Generate tests for different script directories
	generator.add(TestConfig {
		manifest_dir: manifest_dir.clone(),
		test_dir: "tests/scripts/tokenize".to_string(),
		module_name: "tokenize".to_string(),
		test_fn: "test_run".to_string(),
	})?;

	generator.add(TestConfig {
		manifest_dir: manifest_dir.clone(),
		test_dir: "tests/scripts/ast".to_string(),
		module_name: "ast".to_string(),
		test_fn: "test_run".to_string(),
	})?;

	generator.add(TestConfig {
		manifest_dir: manifest_dir.clone(),
		test_dir: "tests/scripts/logical_plan".to_string(),
		module_name: "logical_plan".to_string(),
		test_fn: "test_run".to_string(),
	})?;

	generator.add(TestConfig {
		manifest_dir: manifest_dir.clone(),
		test_dir: "tests/scripts/physical_plan".to_string(),
		module_name: "physical_plan".to_string(),
		test_fn: "test_run".to_string(),
	})?;

	// Generate main module file
	generator.generate()?;

	generators.push(generator);

	// Generate custom stub file for reifydb-rql
	// This crate uses test_run from mod.rs
	let stub_path = std::path::Path::new(&manifest_dir)
		.join("tests")
		.join("generated_tests.rs");

	std::fs::write(
		stub_path,
		r#"// Copyright (c) reifydb.com 2025
// This file is licensed under the AGPL-3.0-or-later, see license.md file

//! Auto-generated test modules
//! 
//! This file is generated by build.rs - DO NOT EDIT
//! 
//! This file includes the auto-generated test modules created by the build script.
//! The tests are generated from the scripts in tests/scripts/ directory.

// Import the test functions from the other test files
// These are used by the generated tests
pub use r#mod::test_run;

// Import the other test modules to access their public functions
mod r#mod;

// Include the generated test modules
pub mod generated;
"#,
	)?;

	Ok(())
}
