[package]
name = "reifydb-network"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
websocket = ["dep:tokio", "dep:tokio-stream"]
client = []
server = []

[dependencies]
reifydb-catalog = { workspace = true }
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

tokio = { workspace = true, features = ["macros", "rt-multi-thread"], optional = true }
tokio-stream = { workspace = true, optional = true }

uuid = { workspace = true }
chrono = { workspace = true }

mio = { version = "0.8", features = ["net", "os-poll"] }
slab = "0.4"
num_cpus = "1.16"
core_affinity = "0.8"
socket2 = { version = "0.5", features = ["all"] }
httparse = "1.8"
base64 = "0.22"
sha1 = "0.10"
anyhow = "1.0"

# websocket
futures-util = { workspace = true }
tokio-tungstenite = { workspace = true }


[dev-dependencies]
reifydb-testing = { workspace = true }
test_each_file = { workspace = true }

[build-dependencies]