[package]
name = "reifydb-network"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
websocket = ["dep:tokio", "dep:tokio-stream"]
client = []
server = []

[dependencies]
reifydb-catalog = { workspace = true }
reifydb-core = { workspace = true }
reifydb-engine = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

tokio = { workspace = true, features = ["macros", "rt-multi-thread"], optional = true }
tokio-stream = { workspace = true, optional = true }

uuid = { workspace = true }
chrono = { workspace = true }


# websocket
futures-util = { workspace = true }
tokio-tungstenite = { workspace = true }


[dev-dependencies]
reifydb-testing = { workspace = true }
test_each_file = { workspace = true }

[build-dependencies]