[package]
name = "tests-integration"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
bs58 = { workspace = true }
ed25519-dalek = { workspace = true }
reifydb-codec = { workspace = true }
reifydb = { workspace = true, features = ["testing"] }
reifydb-sub-metrics = { workspace = true }
reifydb-value = { workspace = true }
reifydb-test-harness = { workspace = true, features = ["auth"] }
