[package]
name = "reifydb-type"
authors.workspace = true
version.workspace = true
edition.workspace = true
license = "MIT"
repository.workspace = true

[features]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

uuid = { workspace = true }
num-bigint = { workspace = true }
bigdecimal = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
